# Generated by Django 2.2 on 2019-09-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_classics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='click numberm'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='like number'),
        ),
    ]
