# Generated by Django 2.2 on 2019-08-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=12, verbose_name='Mobile Phone Number'),
        ),
    ]
