# Generated by Django 2.2 on 2019-09-05 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(max_length=200, upload_to='banner/%Y/%m', verbose_name='image')),
                ('url', models.URLField(verbose_name='visit address')),
                ('index', models.IntegerField(default=0, verbose_name='index')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
