# Generated by Django 2.2 on 2019-08-27 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=20, verbose_name='city')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=50, verbose_name='organization name')),
                ('desc', models.TextField(verbose_name='description')),
                ('tag', models.CharField(default='famous', max_length=10, verbose_name='organization tag')),
                ('category', models.CharField(choices=[('institution', 'institution'), ('person', 'person'), ('university', 'university')], default='institution', max_length=20, verbose_name='category')),
                ('click_nums', models.IntegerField(default=0, verbose_name='ckick numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav numbers')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('course_nums', models.IntegerField(default=0, verbose_name='course number')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=50, verbose_name="teacher's name")),
                ('work_years', models.IntegerField(default=0, verbose_name='work years')),
                ('work_company', models.CharField(max_length=50, verbose_name='work company')),
                ('work_position', models.CharField(max_length=50, verbose_name='position')),
                ('points', models.CharField(max_length=50, verbose_name='points')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav numbers')),
                ('age', models.IntegerField(default=18, verbose_name='age')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='cover image')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
            },
        ),
    ]
